### ISSUE TITLE
0.0.1 effectiveness 

### ISSUE THREAD

**Issue by grahamperrin** [minhducsun2002/just-another-newtab#1]
The shot https://github.com/minhducsun2002/just-another-newtab#user-content-screenshots looks nice but I'm not getting it with either Waterfox 56.2.3 or Firefox 63.0 on FreeBSD …

### Postscript

Note to self, [Simplicity](https://addons.mozilla.org/addon/simplicity-newtab/?src=search) 0.0.1 also known as _Just another new tab page_.

**Comment by minhducsun2002** [comment]
Please describe the issue you encountered precisely.
I tested with Firefox 62.0.3-1 on Debian and I saw no error.

**Comment by grahamperrin** [comment]
There's blankness when opening the first new tab after installation of the extension: 

![2018-10-22 06 52 07 undefined](https://user-images.githubusercontent.com/192271/47279190-55d48780-d5c7-11e8-865f-9ae42b129c07.png)

– and blankness for every new tab thereafter: 

![2018-10-22 06 52 43 mozilla firefox](https://user-images.githubusercontent.com/192271/47279204-6684fd80-d5c7-11e8-84d1-059d3d5b5924.png)

A web console view of things: 

![2018-10-22 06 57 13 mozilla firefox](https://user-images.githubusercontent.com/192271/47279278-c380b380-d5c7-11e8-851c-c7f8d01a4322.png)

**Comment by minhducsun2002** [comment]
It looks like I forgot to include JS files.

New release should fix that. Sorry for any convenience.

**Comment by minhducsun2002** [comment]
Issue solved.

**Comment by grahamperrin** [comment]
Fix confirmed. Thanks!
